#!/usr/bin/env bash
# gen-rust-notices.sh — regenerate LICENSES/RustCrates-NOTICES.txt, the
# full attribution (license text + copyright notice + crate list) for
# every Rust crate compiled into UFB's binaries. MIT / BSD / ISC and
# friends require the notice to travel with the binary; this file
# ships in the installer / app bundle alongside THIRD_PARTY_NOTICES.txt.
#
# Two manifests: the root workspace (core + bindings → ufb) and the
# separate agent crate (ufb-agent). Requires `cargo install cargo-about
# --features cli`. Re-run whenever Cargo.lock or agent/Cargo.lock
# changes; CI could diff the output to catch a stale file.
set -euo pipefail
REPO_ROOT="$(cd "$(dirname "$0")/.." && pwd)"
OUT="$REPO_ROOT/LICENSES/RustCrates-NOTICES.txt"
TPL="$REPO_ROOT/scripts/templates/rust-notices.hbs"
command -v cargo-about >/dev/null || { echo "cargo-about missing: cargo install cargo-about --features cli" >&2; exit 1; }

{
    echo "RUST CRATE NOTICES"
    echo "=================="
    echo
    echo "Generated by scripts/gen-rust-notices.sh (cargo-about) from Cargo.lock"
    echo "and agent/Cargo.lock on $(date -u +%Y-%m-%d). Lists every third-party"
    echo "Rust crate compiled into UFB (ufb / bindings / ufb-core) and ufb-agent,"
    echo "grouped by license, with each license's full text. UFB's own crates"
    echo "are GPL-3.0-or-later (see ../LICENSE)."
    echo
    echo "###############################################################################"
    echo "# ufb (workspace: core + bindings)"
    echo "###############################################################################"
    (cd "$REPO_ROOT" && cargo about generate -c about.toml "$TPL")
    echo
    echo "###############################################################################"
    echo "# ufb-agent"
    echo "###############################################################################"
    (cd "$REPO_ROOT/agent" && cargo about generate -c ../about.toml "$TPL")
} > "$OUT.tmp"
mv "$OUT.tmp" "$OUT"
echo "wrote $OUT ($(wc -l < "$OUT") lines)"
