#!/usr/bin/env bash
# make-appcast.sh — add a release to the committed Sparkle/WinSparkle
# appcasts (docs/appcast-mac.xml, docs/appcast-win.xml). The docs/
# folder is the ufbrowser.com GitHub Pages site, so committing +
# pushing the edited appcast is what publishes the update; the
# binaries themselves live on the GitHub release for the version tag.
#
#   appcast-mac.xml — DOWNLOAD item (since 1.2.0). Enclosure points at
#                     the signed + notarized installer pkg on the GitHub
#                     release; Sparkle verifies the ed25519
#                     sparkle:edSignature and runs a guided package
#                     install (installationType is inferred from the
#                     .pkg extension). Pre-1.2.0 items were informational
#                     (DMG link only) and stay that way in the history.
#   appcast-win.xml — DOWNLOAD item. Enclosure points at the Inno
#                     installer on the GitHub release; the ed25519
#                     sparkle:edSignature is verified by WinSparkle
#                     before it runs the installer.
#
# New items are inserted at the @@APPCAST_INSERT@@ sentinel (newest
# first), so the feed keeps its history.
#
# Usage:
#   scripts/make-appcast.sh <version> <pkg-path> [win-exe-path] [notes-file]
#
# Run AFTER the GitHub release tag v<version> exists (or will exist)
# with the PKG / EXE uploaded under their exact basenames. Then review
# + commit docs/appcast-*.xml to publish.
#
# Signing (both enclosures): uses Sparkle's `sign_update` with the
# private key generated by `generate_keys` (stored in the login
# Keychain) — one key for both OSes. Pass the Windows-built
# UFB-<ver>-x64.exe (copy it to this Mac or a shared path) as
# <win-exe-path> to update appcast-win.xml. Omit it to update only
# appcast-mac.xml.
#
# Requires: sign_update (ships in Sparkle's bin/ — the same
# distribution you took generate_keys from). Looked up on PATH, then
# in the vendored ../QCView-Player/external/Sparkle/bin; override with
# SPARKLE_BIN=~/Sparkle/bin scripts/make-appcast.sh ...

set -euo pipefail

REPO_ROOT="$(cd "$(dirname "$0")/.." && pwd)"
REPO="cbkow/ufb"
MAC_APPCAST="$REPO_ROOT/docs/appcast-mac.xml"
WIN_APPCAST="$REPO_ROOT/docs/appcast-win.xml"
SENTINEL="<!-- @@APPCAST_INSERT@@ -->"

VERSION="${1:?usage: make-appcast.sh <version> <pkg-path> [win-exe-path] [notes-file]}"
PKG_PATH="${2:?need the pkg path}"
WIN_EXE="${3:-}"
NOTES_FILE="${4:-}"

TAG="v$VERSION"
DOWNLOAD_BASE="https://github.com/$REPO/releases/download/$TAG"
if [ -n "${SPARKLE_BIN:-}" ]; then
    SIGN_UPDATE="$SPARKLE_BIN/sign_update"
elif command -v sign_update >/dev/null 2>&1; then
    SIGN_UPDATE="sign_update"
else
    SIGN_UPDATE="$REPO_ROOT/../QCView-Player/external/Sparkle/bin/sign_update"
fi
[ -x "$SIGN_UPDATE" ] || command -v "$SIGN_UPDATE" >/dev/null 2>&1 || {
    echo "ERROR: sign_update not found (set SPARKLE_BIN to Sparkle's bin/)." >&2
    exit 1; }

[ -f "$PKG_PATH" ] || { echo "ERROR: pkg not found: $PKG_PATH" >&2; exit 1; }
PKG_NAME="$(basename "$PKG_PATH")"
PUBDATE="$(date "+%a, %d %b %Y %H:%M:%S %z")"

if [ -n "$NOTES_FILE" ] && [ -f "$NOTES_FILE" ]; then
    NOTES="$(cat "$NOTES_FILE")"
else
    NOTES="UFB $VERSION. See the changelog for details."
fi

# insert_item <appcast-file> <item-xml>: splice the item in right after
# the sentinel line, keeping the sentinel for the next release.
insert_item() {
    local file="$1" item="$2"
    grep -qF "$SENTINEL" "$file" || {
        echo "ERROR: insertion marker missing in $file" >&2; exit 1; }
    if grep -q "<sparkle:version>$VERSION</sparkle:version>" "$file"; then
        echo "$(basename "$file") already has an item for $VERSION — skipping."
        return 0
    fi
    # Splice via a temp file — `awk -v item=` would reinterpret
    # backslash escapes inside release notes.
    local tmp item_file
    tmp="$(mktemp)"
    item_file="$(mktemp)"
    printf '%s\n' "$item" > "$item_file"
    awk -v marker="$SENTINEL" -v itemfile="$item_file" '
        { print }
        index($0, marker) {
            while ((getline line < itemfile) > 0) print line
            close(itemfile)
        }
    ' "$file" > "$tmp"
    mv "$tmp" "$file"
    rm -f "$item_file"
    echo "updated $(basename "$file") with $VERSION"
}

# ── appcast-mac.xml (signed pkg download) ────────────────────────────
# sign_update prints e.g.:  sparkle:edSignature="..." length="12345"
MAC_SIGN_OUT="$("$SIGN_UPDATE" "$PKG_PATH")"
echo "sign_update (mac): $MAC_SIGN_OUT"
MAC_ITEM="    <item>
      <title>Version $VERSION</title>
      <sparkle:version>$VERSION</sparkle:version>
      <sparkle:shortVersionString>$VERSION</sparkle:shortVersionString>
      <sparkle:minimumSystemVersion>14.0</sparkle:minimumSystemVersion>
      <description><![CDATA[$NOTES]]></description>
      <pubDate>$PUBDATE</pubDate>
      <enclosure url=\"$DOWNLOAD_BASE/$PKG_NAME\" type=\"application/octet-stream\" $MAC_SIGN_OUT />
    </item>"
insert_item "$MAC_APPCAST" "$MAC_ITEM"

# ── appcast-win.xml (signed download) ────────────────────────────────
if [ -n "$WIN_EXE" ]; then
    [ -f "$WIN_EXE" ] || { echo "ERROR: win exe not found: $WIN_EXE" >&2; exit 1; }
    EXE_NAME="$(basename "$WIN_EXE")"
    # sign_update prints e.g.:  sparkle:edSignature="..." length="12345"
    SIGN_OUT="$("$SIGN_UPDATE" "$WIN_EXE")"
    echo "sign_update: $SIGN_OUT"

    WIN_ITEM="    <item>
      <title>Version $VERSION</title>
      <sparkle:version>$VERSION</sparkle:version>
      <sparkle:shortVersionString>$VERSION</sparkle:shortVersionString>
      <description><![CDATA[$NOTES]]></description>
      <pubDate>$PUBDATE</pubDate>
      <enclosure url=\"$DOWNLOAD_BASE/$EXE_NAME\" type=\"application/octet-stream\" $SIGN_OUT />
    </item>"
    insert_item "$WIN_APPCAST" "$WIN_ITEM"
else
    echo "(skipped appcast-win.xml — no win-exe-path given)"
fi

echo ""
echo "Publish:"
echo "  1. gh release create $TAG $PKG_PATH${WIN_EXE:+ $WIN_EXE} --title \"UFB $VERSION\""
echo "     (or upload to the existing $TAG release — asset names must match)"
echo "  2. review + commit docs/appcast-*.xml, push — GitHub Pages serves"
echo "     them at https://ufbrowser.com/"
