#!/usr/bin/env bash
# make-appcast.sh — add a release to the committed Sparkle/WinSparkle
# appcasts (docs/appcast-mac.xml, docs/appcast-win.xml). The docs/
# folder is the ufbrowser.com GitHub Pages site, so committing +
# pushing the edited appcast is what publishes the update; the
# binaries themselves live on the GitHub release for the version tag.
#
#   appcast-mac.xml — INFORMATIONAL item. Sparkle can't atomically swap
#                     UFB's multi-bundle drag-install DMG, so the item
#                     carries no enclosure: Sparkle shows the version +
#                     notes and a button that opens the DMG URL in the
#                     browser. Integrity = Developer-ID + notarization.
#   appcast-win.xml — DOWNLOAD item. Enclosure points at the Inno
#                     installer on the GitHub release; the ed25519
#                     sparkle:edSignature is verified by WinSparkle
#                     before it runs the installer.
#
# New items are inserted at the @@APPCAST_INSERT@@ sentinel (newest
# first), so the feed keeps its history.
#
# Usage:
#   scripts/make-appcast.sh <version> <dmg-path> [win-exe-path] [notes-file]
#
# Run AFTER the GitHub release tag v<version> exists (or will exist)
# with the DMG / EXE uploaded under their exact basenames. Then review
# + commit docs/appcast-*.xml to publish.
#
# Signing (Windows enclosure): uses Sparkle's `sign_update` with the
# private key generated by `generate_keys` (stored in the login
# Keychain). Pass the Windows-built UFB-<ver>-x64.exe (copy it to this
# Mac or a shared path) as <win-exe-path> to update appcast-win.xml.
# Omit it to update only appcast-mac.xml.
#
# Requires: sign_update on PATH (ships in Sparkle's bin/ — the same
# distribution you took generate_keys from). Point SPARKLE_BIN at it if
# it isn't on PATH:  SPARKLE_BIN=~/Sparkle/bin scripts/make-appcast.sh ...

set -euo pipefail

REPO_ROOT="$(cd "$(dirname "$0")/.." && pwd)"
REPO="cbkow/ufb"
MAC_APPCAST="$REPO_ROOT/docs/appcast-mac.xml"
WIN_APPCAST="$REPO_ROOT/docs/appcast-win.xml"
SENTINEL="<!-- @@APPCAST_INSERT@@ -->"

VERSION="${1:?usage: make-appcast.sh <version> <dmg-path> [win-exe-path] [notes-file]}"
DMG_PATH="${2:?need the DMG path}"
WIN_EXE="${3:-}"
NOTES_FILE="${4:-}"

TAG="v$VERSION"
DOWNLOAD_BASE="https://github.com/$REPO/releases/download/$TAG"
SIGN_UPDATE="${SPARKLE_BIN:+$SPARKLE_BIN/}sign_update"

DMG_NAME="$(basename "$DMG_PATH")"
PUBDATE="$(date "+%a, %d %b %Y %H:%M:%S %z")"

if [ -n "$NOTES_FILE" ] && [ -f "$NOTES_FILE" ]; then
    NOTES="$(cat "$NOTES_FILE")"
else
    NOTES="UFB $VERSION. See the changelog for details."
fi

# insert_item <appcast-file> <item-xml>: splice the item in right after
# the sentinel line, keeping the sentinel for the next release.
insert_item() {
    local file="$1" item="$2"
    grep -qF "$SENTINEL" "$file" || {
        echo "ERROR: insertion marker missing in $file" >&2; exit 1; }
    if grep -q "<sparkle:version>$VERSION</sparkle:version>" "$file"; then
        echo "$(basename "$file") already has an item for $VERSION — skipping."
        return 0
    fi
    # Splice via a temp file — `awk -v item=` would reinterpret
    # backslash escapes inside release notes.
    local tmp item_file
    tmp="$(mktemp)"
    item_file="$(mktemp)"
    printf '%s\n' "$item" > "$item_file"
    awk -v marker="$SENTINEL" -v itemfile="$item_file" '
        { print }
        index($0, marker) {
            while ((getline line < itemfile) > 0) print line
            close(itemfile)
        }
    ' "$file" > "$tmp"
    mv "$tmp" "$file"
    rm -f "$item_file"
    echo "updated $(basename "$file") with $VERSION"
}

# ── appcast-mac.xml (informational) ──────────────────────────────────
MAC_ITEM="    <item>
      <title>Version $VERSION</title>
      <sparkle:version>$VERSION</sparkle:version>
      <sparkle:shortVersionString>$VERSION</sparkle:shortVersionString>
      <sparkle:minimumSystemVersion>14.0</sparkle:minimumSystemVersion>
      <!-- Informational: no enclosure. Empty informationalUpdate ->
           applies to all installed versions. The button opens link. -->
      <sparkle:informationalUpdate></sparkle:informationalUpdate>
      <link>$DOWNLOAD_BASE/$DMG_NAME</link>
      <description><![CDATA[$NOTES]]></description>
      <pubDate>$PUBDATE</pubDate>
    </item>"
insert_item "$MAC_APPCAST" "$MAC_ITEM"

# ── appcast-win.xml (signed download) ────────────────────────────────
if [ -n "$WIN_EXE" ]; then
    [ -f "$WIN_EXE" ] || { echo "ERROR: win exe not found: $WIN_EXE" >&2; exit 1; }
    command -v "$SIGN_UPDATE" >/dev/null 2>&1 || {
        echo "ERROR: sign_update not found (set SPARKLE_BIN to Sparkle's bin/)." >&2
        exit 1; }

    EXE_NAME="$(basename "$WIN_EXE")"
    # sign_update prints e.g.:  sparkle:edSignature="..." length="12345"
    SIGN_OUT="$("$SIGN_UPDATE" "$WIN_EXE")"
    echo "sign_update: $SIGN_OUT"

    WIN_ITEM="    <item>
      <title>Version $VERSION</title>
      <sparkle:version>$VERSION</sparkle:version>
      <sparkle:shortVersionString>$VERSION</sparkle:shortVersionString>
      <description><![CDATA[$NOTES]]></description>
      <pubDate>$PUBDATE</pubDate>
      <enclosure url=\"$DOWNLOAD_BASE/$EXE_NAME\" type=\"application/octet-stream\" $SIGN_OUT />
    </item>"
    insert_item "$WIN_APPCAST" "$WIN_ITEM"
else
    echo "(skipped appcast-win.xml — no win-exe-path given)"
fi

echo ""
echo "Publish:"
echo "  1. gh release create $TAG $DMG_PATH${WIN_EXE:+ $WIN_EXE} --title \"UFB $VERSION\""
echo "     (or upload to the existing $TAG release — asset names must match)"
echo "  2. review + commit docs/appcast-*.xml, push — GitHub Pages serves"
echo "     them at https://ufbrowser.com/"
